### ISSUE TITLE
Supporting Windows operating system

### ISSUE THREAD

**Issue by kaarimtareek** [NormalNvim/installer#1]
I really liked the philosophy behind this distro, but when I tried to use it on windows many errors popped out, when I checked the the documentation and the section of supported operating system didn't include windows, is there change to support it in the near future?

**Comment by Zeioth** [comment]
@kaarimtareek you can install it on Windows enabling WSL. This is necessary in case you want to use the automated installer to take care of the optional dependencies for you, to enable all features, like compilers and stuff.
